### ISSUE TITLE
How to use it for small Smiles like Aspirin Smile: CC(=O)Oc1ccccc1C(=O)O

### ISSUE THREAD

**Issue by Fatima-Aslam** [EBjerrum/SMILES-enumeration#7]
Whenever, I write any small Smiles string 
Then I get
[22:10:14] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
Traceback (most recent call last):
  File "SmilesEnumerator.py", line 272, in <module>
    from SmilesEnumerator import SmilesEnumerator
  File "D:\MSCS (fatima)\medicinal plants\Research task (August)\Synopsis\SmilesEnumerationCode - Copy\SMILES-enumeration-master (1)\SMILES-enumeration-master\SmilesEnumerator.py", line 276, in <module>
    print(sme.randomize_smiles("COc1cnc(nC1N(C)C)c2ccccc2"))
  File "D:\MSCS (fatima)\medicinal plants\Research task (August)\Synopsis\SmilesEnumerationCode - Copy\SMILES-enumeration-master (1)\SMILES-enumeration-master\SmilesEnumerator.py", line 170, in randomize_smiles
    ans = list(range(m.GetNumAtoms()))
AttributeError: 'NoneType' object has no attribute 'GetNumAtoms'

Please help me to resolve this issue

**Comment by EBjerrum** [comment]
I don't think your SMILES are getting parsed by RDKit. All smiles must be parsable by RDKit

Chem.MolFromSmiles("COc1cnc(nC1N(C)C)c2ccccc2")
RDKit ERROR: [13:54:15] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
RDKit ERROR: 

In this particular instance I think you need to tell RDKit on which aromatic nitrogen the hydrogen is situated.

**Comment by Fatima-Aslam** [comment]
Thank you for your reply
I have an another question, Everytime I run the code it generates 10
different SMILES against a single a same input SMILE. Can you please
explain it?
Regards
Fatima

**Comment by EBjerrum** [comment]
Data augmentation with SMILES enumeration is all about generating alternative SMILES for the same molecule.
